name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - lmfit
  - flopy
  - simplekml
  - xlrd
  - openpyxl
  - scikit-learn
  - geopandas=0.3.0
